version: '3'
services:
  react_app:
    build: ./vite-front-end
    ports:
      - "5173:5173"
  node_app:
    build: ./back-end/express-server
    ports:
      - "3030:3030"
    depends_on:
      - flask_app
    environment:
      - NODE_ENV=development
      - API_PORT=3030
  flask_app:
    build: ./back-end/python
    ports:
      - "5000:5000"
  nginx:
    container_name: nginx
    depends_on:
      - react_app
      - node_app
    ports:
      - "8080:80"
    build: ./nginx